outlook:
  client_id: <enter client id here from microsoft onegraph>
  secret_id: <enter client secret here from microsoft onegraph>
  test_email: <enter a email you have access to for testing>

gmail:
  sender_email: <enter the gmail account authorized>
  test_email: <enter the email address to send a message to here>
